# Generated by Django 6.0.2 on 2026-02-25 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(
                blank=True, help_text='Краткая информация', max_length=500, null=True, verbose_name='о себе'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True, help_text='Аватар', null=True, upload_to='avatars/', verbose_name='аватарка'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Город', max_length=100, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Подтвержден ли email', verbose_name='подтвержден'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                blank=True, help_text='Номер телефона', max_length=20, null=True, verbose_name='телефон'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('user', 'Обычный пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')],
                default='user',
                help_text='Роль',
                max_length=20,
                verbose_name='роль',
            ),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'payment_date',
                    models.DateTimeField(
                        auto_now_add=True, help_text='Дата и время совершения платежа', verbose_name='дата оплаты'
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2, help_text='Сумма платежа', max_digits=10, verbose_name='сумма оплаты'
                    ),
                ),
                (
                    'payment_method',
                    models.CharField(
                        choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')],
                        default='cash',
                        help_text='Способ оплаты: наличные или перевод на счет',
                        max_length=20,
                        verbose_name='способ оплаты',
                    ),
                ),
                (
                    'paid_course',
                    models.ForeignKey(
                        blank=True,
                        help_text='Курс, который был оплачен',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='payments',
                        to='materials.course',
                        verbose_name='оплаченный курс',
                    ),
                ),
                (
                    'paid_lesson',
                    models.ForeignKey(
                        blank=True,
                        help_text='Урок, который был оплачен',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='payments',
                        to='materials.lesson',
                        verbose_name='оплаченный урок',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='Пользователь, совершивший платеж',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
    ]
