# Generated by Django 6.0.3 on 2026-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_about_alter_user_avatar_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(
                choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('failed', 'Ошибка')],
                default='pending',
                max_length=20,
                verbose_name='статус оплаты',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID цены в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оплату Stripe'),
        ),
    ]
