# Generated by Django 6.0.2 on 2026-02-23 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название курса', max_length=200, verbose_name='название')),
                (
                    'preview',
                    models.ImageField(
                        blank=True,
                        help_text='Превью курса',
                        null=True,
                        upload_to='courses/previews/',
                        verbose_name='превью',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, help_text='Описание курса', null=True, verbose_name='описание'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        help_text='Владелец курса',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='courses_owned',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='владелец',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название урока', max_length=200, verbose_name='название')),
                (
                    'description',
                    models.TextField(blank=True, help_text='Описание урока', null=True, verbose_name='описание'),
                ),
                (
                    'preview',
                    models.ImageField(
                        blank=True,
                        help_text='Превью урока',
                        null=True,
                        upload_to='lessons/previews/',
                        verbose_name='превью',
                    ),
                ),
                (
                    'video_url',
                    models.URLField(
                        blank=True,
                        help_text='Ссылка на видео (YouTube, Vimeo и т.д.)',
                        max_length=500,
                        null=True,
                        verbose_name='ссылка на видео',
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(
                        default=0, help_text='Порядковый номер урока в курсе', verbose_name='порядок'
                    ),
                ),
                (
                    'duration',
                    models.DurationField(
                        blank=True, help_text='Длительность урока', null=True, verbose_name='длительность'
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(default=True, help_text='Опубликован ли урок', verbose_name='опубликован'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                (
                    'course',
                    models.ForeignKey(
                        help_text='Курс, к которому относится урок',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lessons',
                        to='materials.course',
                        verbose_name='курс',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        help_text='Владелец урока',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lessons_owned',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='владелец',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['course', 'order', 'created_at'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
