# Generated by Django 6.0.2 on 2026-03-14 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(
                blank=True,
                help_text='Ссылка на видео (разрешен только YouTube)',
                max_length=500,
                null=True,
                verbose_name='ссылка на видео',
            ),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, help_text='Дата и время подписки', verbose_name='дата подписки'
                    ),
                ),
                (
                    'course',
                    models.ForeignKey(
                        help_text='Курс, на который подписан пользователь',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriptions',
                        to='materials.course',
                        verbose_name='курс',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='Пользователь, который подписался на обновления',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriptions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
