# Generated by Django 6.0.3 on 2026-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_video_url_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_notification_sent',
            field=models.DateTimeField(
                blank=True,
                help_text='Время последней отправки уведомления об обновлении',
                null=True,
                verbose_name='Время последнего уведомления',
            ),
        ),
    ]
